import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'FantasticPower',
  description: 'Generated by create next app',
}

import Head from 'next/head'

export default function RootLayout({ children }) {
  return (
    <>
      <Head>
        <title>FantasticPower</title>
        <meta property="og:title" content="FantasticPower" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://fantasticpower.vercel.app/" />
        <meta property="og:image" content="https://fantasticpower.vercel.app/cringe.jpg" />
        <meta property="og:description" content="Site description" />
      </Head>
      {children}
    </>
  );
}